### ISSUE TITLE
What is Difference between useEffect vs useLayoutEffect in React.js

### ISSUE THREAD

**Issue by LouisDouglas** [devlouis98/ETHDivide#1]
Please help me, urgently must

**Comment by devlouis98** [comment]
The difference between them is the timing of their invocation.
useEffect runs asynchronously after a render is painted to the screen, unblocking the browser paint process.
So that looks like:

We cause a render somehow (through the state, or the parent re-renders or context change). In our case by clicking on the Increment button.
React updates the state internally. Counter value gets updated to 1.
React handles the DOM mutation.
Count: 0
gets changed to
Count: 1
The browser paints this DOM change to the browser’s screen. In our case Count: 1 is painted on the screen.
The useEffect function is fired after the browser has painted the DOM changes. Prints useEffect is fired.
However, useLayoutEffect fires synchronously after all DOM mutations.
So that looks like:
We cause a render somehow (through the state, or the parent re-renders or context change). In our case by clicking on the Increment button.
React updates the state internally. Counter value gets updated to 1.
React handles the DOM mutation.
Count: 0
gets changed to
Count: 1
useLayoutEffect is fired immediately after the DOM mutations.
The browser paints this DOM change to the browser’s screen. In our case Count: 1 is painted on the screen.
In simple words, useLayoutEffect doesn’t care whether the browser has painted the DOM changes or not. It triggers the function right after the DOM mutations are computed.

**Comment by devlouis98** [comment]
> Please help me, urgently must

The difference between them is the timing of their invocation.
useEffect runs asynchronously after a render is painted to the screen, unblocking the browser paint process.
So that looks like:

We cause a render somehow (through the state, or the parent re-renders or context change). In our case by clicking on the Increment button.
React updates the state internally. Counter value gets updated to 1.
React handles the DOM mutation.
Count: 0
gets changed to
Count: 1
The browser paints this DOM change to the browser’s screen. In our case Count: 1 is painted on the screen.
The useEffect function is fired after the browser has painted the DOM changes. Prints useEffect is fired.
However, useLayoutEffect fires synchronously after all DOM mutations.
So that looks like:
We cause a render somehow (through the state, or the parent re-renders or context change). In our case by clicking on the Increment button.
React updates the state internally. Counter value gets updated to 1.
React handles the DOM mutation.
Count: 0
gets changed to
Count: 1
useLayoutEffect is fired immediately after the DOM mutations.
The browser paints this DOM change to the browser’s screen. In our case Count: 1 is painted on the screen.
In simple words, useLayoutEffect doesn’t care whether the browser has painted the DOM changes or not. It triggers the function right after the DOM mutations are computed.

**Comment by LouisDouglas** [comment]
Thank you!
